using System.ComponentModel.DataAnnotations;

namespace RoboticsManagement.ViewModels
{
    public class EmployeeRegistrationViewModel
    {
        [Required(ErrorMessage = "User name is required")]
        public string UserName { get; set; }
        [Required]
        [DataType(DataType.Password, ErrorMessage = "Invalid password")]
        public string Password { get; set; } //todo create autogenerated password and send to mail or sth token with possibitlity to change password
        [Compare("Password", ErrorMessage = "Password and Confirm Password doesn't match")]
        public string ConfirmPassword { get; set; }
        [Required]
        [EmailAddress]
        [MaxLength(50, ErrorMessage = "Too long email")]
        public string Email { get; set; }
        [Phone(ErrorMessage = "Invalid phone number")]
        public string PhoneNumber { get; set; }
        [Required]
        [MaxLength(30)]
        public string FirstName { get; set; }
        [Required]
        [MaxLength(30)]
        public string LastName { get; set; }
        [Required]
        [MaxLength(9, ErrorMessage = "Invalid Zip Code"), MinLength(5, ErrorMessage = "Invalid Zip Code")]
        public string ZipCode { get; set; }
        [Required]
        [StringLength(50, ErrorMessage = "Invalid City, name is too long.")]
        public string City { get; set; }
        [Required]
        [StringLength(30, ErrorMessage = "Invalid Country, name is too long.")]
        public string Country { get; set; }
        [Required]
        [StringLength(70, ErrorMessage = "Invalid Adress, address is too long.")]
        public string Adress { get; set; }
    }
}
